var mounts = [
    { "itemName": "Arcane Whirlwind", "slots": "BUU", "quality": "legendary", "legacyMount": false, "equipPower": "+4,000 Power", "combatPower": "Summons your Arcane Whirlwind, who travels forward, dealing 2,796 damage to nearby enemies, and knocking aside enemies it collides with for an additional 5,591 damage.", "qualitySort": 1 },
    { "itemName": "Armored Axe Beak", "slots": "CUU", "quality": "legendary", "legacyMount": false, "equipPower": "+4,000 Armor Penetration", "combatPower": "Summons your armored axe beak to attack nearby foes with a spinning strike dealing 6,989 to targets hit.", "qualitySort": 1 },
    { "itemName": "Armored Bulette", "slots": "CUU", "quality": "legendary", "legacyMount": false, "equipPower": "+4,000 Deflection", "combatPower": "Summons your Armored Bulette, who roars at foes in front of you, dealing 3,994 damage and reducing the damage they deal by 10% for 8 seconds.", "qualitySort": 1 },
    { "itemName": "Armored Giant Strider", "slots": "IUU", "quality": "legendary", "legacyMount": false, "equipPower": "+4,000 Movement", "combatPower": "Summons your Armored Giant Strider to attack your target, dealing 3,455 Fire Damage damage.", "qualitySort": 1 },
    { "itemName": "Armored Griffon", "slots": "CUU", "quality": "legendary", "legacyMount": false, "equipPower": "Activating an Artifact power reduces all of your cooldowns by 35%.", "combatPower": "Summon your Armored Griffon to release an earsplitting screech, reducing the damage nearby enemies deal by 30% for 6 seconds.", "qualitySort": 1 },
    { "itemName": "Beholder Personal Tank", "slots": "EUU", "quality": "legendary", "legacyMount": false, "equipPower": "Reduce the damage effect of Combat Advantage against you by 50%.", "combatPower": "Summon your Beholder Personal Tank to blast enemies with disintegration beams in a line, dealing 6,989 damage. Any targets with less remaining health than your total Power take 500% normal damage and are disintegrated if killed.", "qualitySort": 1 },
    { "itemName": "Black Ice Warhorse", "slots": "BUU", "quality": "legendary", "legacyMount": false, "equipPower": "+4,000 Power", "combatPower": "Summons your Black Ice Warhorse, who deals 3,494 Lightning Damage every 0.5 seconds for 1.5 seconds.", "qualitySort": 1 },
    { "itemName": "Celestial Stag", "slots": "IUU", "quality": "legendary", "legacyMount": false, "equipPower": "+2,000 Recovery +2,000 Regeneration", "combatPower": "Summon your Celestial Stag that brings with it a rain of stars for 8 seconds, continually causing 699 damage to your enemies and slowing their Run Speed by 10%.", "qualitySort": 1 },
    { "itemName": "Champion's Armored Bulette", "slots": "CUU", "quality": "legendary", "legacyMount": false, "equipPower": "+4,000 Deflection", "combatPower": "Summons your Champion's Armored Bulette, who roars at foes in front of you. Dealing 3,994 Thunder Damage and Stunning them for 2 seconds (1 second if target is a player).", "qualitySort": 1 },
    { "itemName": "Coastal Flail Snail", "slots": "BUU", "quality": "legendary", "legacyMount": false, "equipPower": "Using a Daily Power grants 25% of your total Action Points over 10 seconds", "combatPower": "Summons your Flail Snail to knock enemies aside, dealing 1,727 to targets hit.", "qualitySort": 1 },
    { "itemName": "Commander Tyrannosaur", "slots": "RUU", "quality": "legendary", "legacyMount": false, "equipPower": "+2,000 Power +2,000 Armor Penetration", "combatPower": "Summons the Tyrannosaur, causing your enemies fear, rooting them for 5 seconds, and lowering their defense by 10% for 10 seconds.\r\nIf targeting a minion, the Tyrannosaurus will consume them.", "qualitySort": 1 },
    { "itemName": "Emperor Beetle", "slots": "RUU", "quality": "legendary", "legacyMount": false, "equipPower": "+4,000 Defense", "combatPower": "Summons your Emperor Beetle, who flies in and lands violently, dealing 3,494 and Stunning nearby foes for 2 seconds (1 second if target is a player).", "qualitySort": 1 },
    { "itemName": "Imperial Rage Drake", "slots": "RUU", "quality": "legendary", "legacyMount": false, "equipPower": "+4,000 Critical Strike", "combatPower": "Summons your Imperial Rage Drake, who rushes forward, dealing 4,659 Fire Damage and igniting foes, causing them to take an additional 4,659 Fire Damage over 4 seconds (1,165 Fire Damage every second).", "qualitySort": 1 },
    { "itemName": "Legendary Carpet of Flying", "slots": "IUU", "quality": "legendary", "legacyMount": false, "equipPower": "+4,000 Defense", "combatPower": "The Carpet of Flying rushes in and circles the target causing a vortex which pulls nearby enemies towards the center. All enemies caught in the vortex take periodic damage based on their level.", "qualitySort": 1 },
    { "itemName": "Runeclad Manticore", "slots": "BUU", "quality": "legendary", "legacyMount": false, "equipPower": "+1000 Power and Defense\r\n+500 Power and Defense to party members within 50'", "combatPower": "Summon your Runeclad Manticore to unleash a torrent of spines from its barbed tail upon your foes, dealing 1,456 damage in a cone, knocking them back and pinning them down for 1.5 seconds.", "qualitySort": 1 },
    { "itemName": "Skeleton Steed", "slots": "IUU", "quality": "legendary", "legacyMount": false, "equipPower": "Using a Daily Power grants 20% of your total Hit Points over 10 seconds.", "combatPower": "Your Skeletal Steed unieashes a trail of ink black smoke, withering foes in front of you for 6 seconds, Slowing them and dealing 1,398 Necrotic Damage every second.", "qualitySort": 1 },
    { "itemName": "Swift Golden Lion", "slots": "IUU", "quality": "legendary", "legacyMount": false, "equipPower": "When you or a party member are struck by a foe, there is a chance they will be healed and you will gain a stack of Radiant Weapon.", "combatPower": "Summon your Celestial Lion to knock back nearby foes and grant nearby party members a Shield for 10 seconds. After 10 seconds, affected party members gain up to 3 stacks of Radiant Weapon based on the amount shield remaining.", "qualitySort": 1 },
    { "itemName": "Tenser's Floating Disk", "slots": "EUU", "quality": "legendary", "legacyMount": false, "equipPower": "+4,000 Recovery", "combatPower": "You are transformed into a virtual fighting machine, becoming stronger, tougher, faster, and more skilled in combat. For 12 seconds, you gain 10% Power and move 10% faster, and gain +2 Strength, Dexterity, Constitution, and Armor Class.", "qualitySort": 1 },
    { "itemName": "War Triceratops", "slots": "RUU", "quality": "legendary", "legacyMount": false, "equipPower": "+16,000 Maximum Hit Points", "combatPower": "Summon your War Triceratops to change into the fray knocking back foes and causing up to 15,000 damage to each target, based on your level.", "qualitySort": 1 },
    { "itemName": "Warpainted Tyrannosaur", "slots": "RUU", "quality": "legendary", "legacyMount": false, "equipPower": "+2,000 Power +2,000 Armor Penetration", "combatPower": "Summons the Tyrannosaur, causing your enemies fear, rooting them for 5 seconds, and lowering their defense by 10% for 10 seconds.\r\nIf targeting a minion, the Tyrannosaurus will consume them.", "qualitySort": 1 },
    { "itemName": "Apparatus of Gond", "slots": "REU", "quality": "epic", "legacyMount": false, "equipPower": "+2,000 Power", "combatPower": "", "qualitySort": 2 },
    { "itemName": "Apparatus of Kwalish", "slots": "EEU", "quality": "epic", "legacyMount": false, "equipPower": "+2,000 Recovery", "combatPower": "", "qualitySort": 2 },
    { "itemName": "Armored Bear", "slots": "CRU", "quality": "epic", "legacyMount": false, "equipPower": "+8,000 Maximum Hit Points", "combatPower": "", "qualitySort": 2 },
    { "itemName": "Axe Beak", "slots": "BIU", "quality": "epic", "legacyMount": false, "equipPower": "+2,000 Armor Penetration", "combatPower": "", "qualitySort": 2 },
    { "itemName": "Black Owlbear", "slots": "CCU", "quality": "epic", "legacyMount": false, "equipPower": "+8,000 Maximum Hit Points", "combatPower": "", "qualitySort": 2 },
    { "itemName": "Blazing Yeth Hound", "slots": "BIU", "quality": "epic", "legacyMount": true, "equipPower": null, "combatPower": null, "qualitySort": 2 },
    { "itemName": "Blueforged Rage Drake", "slots": "BIU", "quality": "epic", "legacyMount": false, "equipPower": "+2,000 Critical Strike", "combatPower": "", "qualitySort": 2 },
    { "itemName": "Bulette", "slots": "CRU", "quality": "epic", "legacyMount": false, "equipPower": "+2,000 Deflection", "combatPower": "", "qualitySort": 2 },
    { "itemName": "Carpet of Flying", "slots": "IUU", "quality": "epic", "legacyMount": false, "equipPower": "+2,000 Defense", "combatPower": "", "qualitySort": 2 },
    { "itemName": "Cavalry Tyrannosaur", "slots": "RBU", "quality": "epic", "legacyMount": false, "equipPower": "+1,000 Power +1,000 Armor Penetration", "combatPower": "", "qualitySort": 2 },
    { "itemName": "Dawn Unicorn", "slots": "RIU", "quality": "epic", "legacyMount": false, "equipPower": "Using a Daily Power grants 10% of your total Hit Points over 10 seconds.", "combatPower": "", "qualitySort": 2 },
    { "itemName": "Dusk Unicorn", "slots": "CEU", "quality": "epic", "legacyMount": false, "equipPower": "+2,000 Life Steal", "combatPower": "", "qualitySort": 2 },
    { "itemName": "Elite Shadow Wolf", "slots": "CIU", "quality": "epic", "legacyMount": false, "equipPower": "+2,000 Armor Penetration", "combatPower": "", "qualitySort": 2 },
    { "itemName": "Embellished Apparatus of Gond", "slots": "CEU", "quality": "epic", "legacyMount": false, "equipPower": "Using a Daily Power grants 15% of your total Action Points over 10 seconds.", "combatPower": "", "qualitySort": 2 },
    { "itemName": "Enchanted Courser", "slots": "IBU", "quality": "epic", "legacyMount": false, "equipPower": "+2,000 Recovery", "combatPower": "", "qualitySort": 2 },
    { "itemName": "Flail Snail", "slots": "BBU", "quality": "epic", "legacyMount": false, "equipPower": "Using a Daily Power grants 15% of your total Action Points over 10 seconds.", "combatPower": "", "qualitySort": 2 },
    { "itemName": "Frozen Yeth Hound", "slots": "BEU", "quality": "epic", "legacyMount": true, "equipPower": null, "combatPower": null, "qualitySort": 2 },
    { "itemName": "Fungal Flail Snail", "slots": "BBU", "quality": "epic", "legacyMount": false, "equipPower": "+2,000 Recovery", "combatPower": "", "qualitySort": 2 },
    { "itemName": "Gas Spore", "slots": "IEU", "quality": "epic", "legacyMount": false, "equipPower": "Increases your Stamina Regeneration by 20%.\r\nStamina Regeneration is increased by an additional 10% while under the effect of Underdark Mount & Companion Affinity.", "combatPower": "", "qualitySort": 2 },
    { "itemName": "Giant Beetle", "slots": "RRU", "quality": "epic", "legacyMount": false, "equipPower": "+2,000 Defense", "combatPower": "", "qualitySort": 2 },
    { "itemName": "Giant Crab", "slots": "RBU", "quality": "epic", "legacyMount": false, "equipPower": "+2,000 Defense", "combatPower": "", "qualitySort": 2 },
    { "itemName": "Giant Strider", "slots": "IIU", "quality": "epic", "legacyMount": false, "equipPower": "+2,000 Movement", "combatPower": "", "qualitySort": 2 },
    { "itemName": "Gorgon", "slots": "REU", "quality": "epic", "legacyMount": false, "equipPower": "Using a Daily Power grants 15% of your total Action Points over 10 seconds.", "combatPower": "", "qualitySort": 2 },
    { "itemName": "Griffon", "slots": "CIU", "quality": "epic", "legacyMount": false, "equipPower": "Activating an Artifact power reduces all of your cooldowns by 20%.", "combatPower": "", "qualitySort": 2 },
    { "itemName": "Guard Drake", "slots": "RBU", "quality": "epic", "legacyMount": false, "equipPower": "+2,000 Power", "combatPower": "", "qualitySort": 2 },
    { "itemName": "Heavy Giant Spider", "slots": "RIU", "quality": "epic", "legacyMount": false, "equipPower": "+2,000 Power", "combatPower": "", "qualitySort": 2 },
    { "itemName": "Heavy Howler", "slots": "CBU", "quality": "epic", "legacyMount": false, "equipPower": "+2,000 Critical Strike", "combatPower": "", "qualitySort": 2 },
    { "itemName": "Heavy Inferno Nightmare", "slots": "CIU", "quality": "epic", "legacyMount": false, "equipPower": "+2,000 Life Steal", "combatPower": "", "qualitySort": 2 },
    { "itemName": "Heavy Mystic Nightmare", "slots": "IEU", "quality": "epic", "legacyMount": false, "equipPower": "+2,000 Life Steal", "combatPower": "", "qualitySort": 2 },
    { "itemName": "Heavy Twilight Nightmare", "slots": "CCU", "quality": "epic", "legacyMount": false, "equipPower": "+2,000 Power", "combatPower": "", "qualitySort": 2 },
    { "itemName": "Heavy Worg", "slots": "BEU", "quality": "epic", "legacyMount": false, "equipPower": "+1,000 Critical Strike +1,000 Armor Penetration", "combatPower": "", "qualitySort": 2 },
    { "itemName": "High Forest Bear", "slots": "CRU", "quality": "epic", "legacyMount": false, "equipPower": "+8,000 Maximum Hit Points", "combatPower": "", "qualitySort": 2 },
    { "itemName": "Leopard of Chult", "slots": "BIU", "quality": "epic", "legacyMount": false, "equipPower": "+2,000 Recovery", "combatPower": "", "qualitySort": 2 },
    { "itemName": "Lord's Armored Polar Bear", "slots": "RIU", "quality": "epic", "legacyMount": false, "equipPower": "+2,000 Defense", "combatPower": "", "qualitySort": 2 },
    { "itemName": "Manticore", "slots": "BEU", "quality": "epic", "legacyMount": false, "equipPower": "+500 Power and Defense\r\n+250 Power and Defense to party members within 50'", "combatPower": "", "qualitySort": 2 },
    { "itemName": "Medium Adventurer's Horse", "slots": "CBU", "quality": "epic", "legacyMount": false, "equipPower": "+2,000 Movement", "combatPower": "", "qualitySort": 2 },
    { "itemName": "Owlbear", "slots": "CEU", "quality": "epic", "legacyMount": false, "equipPower": "+8,000 Hit Point", "combatPower": "", "qualitySort": 2 },
    { "itemName": "Purple Owlbear", "slots": "RRU", "quality": "epic", "legacyMount": false, "equipPower": "+2,000 Power", "combatPower": "", "qualitySort": 2 },
    { "itemName": "Rage Drake", "slots": "BIU", "quality": "epic", "legacyMount": false, "equipPower": "+2,000 Critical Strike", "combatPower": "", "qualitySort": 2 },
    { "itemName": "Royal Winter Sled", "slots": "EU", "quality": "epic", "legacyMount": false, "equipPower": "+500 Power and Defense\r\n+250 Power and Defense to party members within 50'", "combatPower": "", "qualitySort": 2 },
    { "itemName": "Savage Polar Bear", "slots": "BBU", "quality": "epic", "legacyMount": false, "equipPower": "+1,000 Defense +1,000 Deflection", "combatPower": "", "qualitySort": 2 },
    { "itemName": "Siegebreaker Griffon", "slots": "CIU", "quality": "epic", "legacyMount": false, "equipPower": "+1,000 Defense +1,000 Deflection", "combatPower": "", "qualitySort": 2 },
    { "itemName": "Silverback Bear", "slots": "IEU", "quality": "epic", "legacyMount": false, "equipPower": "Using a Daily Power grants 10% of your total Hit Points over 10 seconds.", "combatPower": "", "qualitySort": 2 },
    { "itemName": "Skeletal Worg", "slots": "BBU", "quality": "epic", "legacyMount": false, "equipPower": "+1,000 Power +1,000 Armor Penetration", "combatPower": "", "qualitySort": 2 },
    { "itemName": "Spiked Deinonychus", "slots": "REU", "quality": "epic", "legacyMount": false, "equipPower": "+1,000 Recovery +1,000 Defense", "combatPower": "", "qualitySort": 2 },
    { "itemName": "Starfade Stag", "slots": "IEU", "quality": "epic", "legacyMount": false, "equipPower": "+1,000 Recovery +1,000 Regeneration", "combatPower": "", "qualitySort": 2 },
    { "itemName": "Stormraider Clydesdale", "slots": "REU", "quality": "epic", "legacyMount": false, "equipPower": "+2,000 Movement", "combatPower": "", "qualitySort": 2 },
    { "itemName": "Striped Owlbear", "slots": "IIU", "quality": "epic", "legacyMount": false, "equipPower": "+2,000 Defense", "combatPower": "", "qualitySort": 2 },
    { "itemName": "Suratuk's Banded Spider", "slots": "CRU", "quality": "epic", "legacyMount": false, "equipPower": "+2,000 Life Steal", "combatPower": "", "qualitySort": 2 },
    { "itemName": "Suratuk's Blue Tarantula", "slots": "BBU", "quality": "epic", "legacyMount": false, "equipPower": "+2,000 Critical Strike", "combatPower": "", "qualitySort": 2 },
    { "itemName": "Suratuk's Giant Red Crab", "slots": "RBU", "quality": "epic", "legacyMount": false, "equipPower": "+2,000 Defense", "combatPower": "", "qualitySort": 2 },
    { "itemName": "Sylvan Stag", "slots": "BEU", "quality": "epic", "legacyMount": false, "equipPower": "Using a Daily Power grants 10% of your total Hit Points over 10 seconds.", "combatPower": "", "qualitySort": 2 },
    { "itemName": "Tiger-striped Owlbear", "slots": "BBU", "quality": "epic", "legacyMount": false, "equipPower": "+2,000 Armor Penetration", "combatPower": "", "qualitySort": 2 },
    { "itemName": "Triceratops", "slots": "RBU", "quality": "epic", "legacyMount": false, "equipPower": "+8,000 Maximum Hit Points", "combatPower": "", "qualitySort": 2 },
    { "itemName": "Turmish Lion", "slots": "IRU", "quality": "epic", "legacyMount": false, "equipPower": "When you or a party member are struck by a foe, there is a chance you will gain a stack of Ferocity, granting you 2% additional damage as physical damage for 10 seconds. Thi effect may stack up to 3 times.", "combatPower": "", "qualitySort": 2 },
    { "itemName": "Whirlwind", "slots": "BBU", "quality": "epic", "legacyMount": false, "equipPower": "+2,000 Power", "combatPower": "", "qualitySort": 2 },
    { "itemName": "White Owlbear", "slots": "EEU", "quality": "epic", "legacyMount": false, "equipPower": "+2,000 Recovery", "combatPower": "", "qualitySort": 2 },
    { "itemName": "White Tiger", "slots": "RBU", "quality": "epic", "legacyMount": false, "equipPower": "+2,000 Armor Penetration", "combatPower": "", "qualitySort": 2 },
    { "itemName": "Yeth Hound", "slots": "CBU", "quality": "epic", "legacyMount": false, "equipPower": "+2,000 Deflection", "combatPower": "", "qualitySort": 2 },
    { "itemName": "Aberrant Drake", "slots": "BII", "quality": "rare", "legacyMount": false, "equipPower": "", "combatPower": "", "qualitySort": 3 },
    { "itemName": "Aberrant Fey Wolf", "slots": "REE", "quality": "rare", "legacyMount": false, "equipPower": "", "combatPower": "", "qualitySort": 3 },
    { "itemName": "Aberrant Gorgon", "slots": "BIU", "quality": "rare", "legacyMount": false, "equipPower": "", "combatPower": "", "qualitySort": 3 },
    { "itemName": "Aberrant Yeth Hound", "slots": "RCC", "quality": "rare", "legacyMount": false, "equipPower": "", "combatPower": "", "qualitySort": 3 },
    { "itemName": "Arkaiun Courser", "slots": "RRB", "quality": "rare", "legacyMount": false, "equipPower": "", "combatPower": "", "qualitySort": 3 },
    { "itemName": "Armored Ghost Horse", "slots": "CCB", "quality": "rare", "legacyMount": false, "equipPower": "", "combatPower": "", "qualitySort": 3 },
    { "itemName": "Black Stallion", "slots": "RIE", "quality": "rare", "legacyMount": false, "equipPower": "", "combatPower": "", "qualitySort": 3 },
    { "itemName": "Buckskin Destrier", "slots": "BBE", "quality": "rare", "legacyMount": false, "equipPower": "", "combatPower": "", "qualitySort": 3 },
    { "itemName": "Eku's Titivated Lion", "slots": "ERC", "quality": "rare", "legacyMount": false, "equipPower": "", "combatPower": "", "qualitySort": 3 },
    { "itemName": "Fey Gorgon", "slots": "EIU", "quality": "rare", "legacyMount": false, "equipPower": "", "combatPower": "", "qualitySort": 3 },
    { "itemName": "Firesoul Gorgon", "slots": "CEU", "quality": "rare", "legacyMount": false, "equipPower": "", "combatPower": "", "qualitySort": 3 },
    { "itemName": "Forest Flail Snail", "slots": "BBU", "quality": "rare", "legacyMount": false, "equipPower": "", "combatPower": "", "qualitySort": 3 },
    { "itemName": "Forest Wolf of the Wild Hunt", "slots": "CII", "quality": "rare", "legacyMount": true, "equipPower": null, "combatPower": null, "qualitySort": 3 },
    { "itemName": "Frosted Wolf of the Wild Hunt", "slots": "CEE", "quality": "rare", "legacyMount": true, "equipPower": null, "combatPower": null, "qualitySort": 3 },
    { "itemName": "Frozen Demon Sled", "slots": "CCR", "quality": "rare", "legacyMount": false, "equipPower": "", "combatPower": "", "qualitySort": 3 },
    { "itemName": "Frozen Winter Sled", "slots": "EU", "quality": "rare", "legacyMount": false, "equipPower": "", "combatPower": "", "qualitySort": 3 },
    { "itemName": "Gelatinous Cube", "slots": "RII", "quality": "rare", "legacyMount": false, "equipPower": "", "combatPower": "", "qualitySort": 3 },
    { "itemName": "Gilded Giant Spider", "slots": "CRI", "quality": "rare", "legacyMount": false, "equipPower": "", "combatPower": "", "qualitySort": 3 },
    { "itemName": "Golden Brindle Horse", "slots": "RRE", "quality": "rare", "legacyMount": false, "equipPower": "", "combatPower": "", "qualitySort": 3 },
    { "itemName": "Green Owlbear", "slots": "CEE", "quality": "rare", "legacyMount": true, "equipPower": null, "combatPower": null, "qualitySort": 3 },
    { "itemName": "Hell Emblazon Worg", "slots": "IEE", "quality": "rare", "legacyMount": false, "equipPower": "", "combatPower": "", "qualitySort": 3 },
    { "itemName": "Hell Hound", "slots": "CCR", "quality": "rare", "legacyMount": false, "equipPower": "", "combatPower": "", "qualitySort": 3 },
    { "itemName": "Howler", "slots": "CBE", "quality": "rare", "legacyMount": false, "equipPower": "", "combatPower": "", "qualitySort": 3 },
    { "itemName": "Medium Black Horse", "slots": "RRB", "quality": "rare", "legacyMount": false, "equipPower": "", "combatPower": "", "qualitySort": 3 },
    { "itemName": "Medium Palomino Horse", "slots": "CBE", "quality": "rare", "legacyMount": false, "equipPower": "", "combatPower": "", "qualitySort": 3 },
    { "itemName": "Medium Pharaoh Steed", "slots": "CCB", "quality": "rare", "legacyMount": false, "equipPower": "", "combatPower": "", "qualitySort": 3 },
    { "itemName": "Medium Snowswift Horse", "slots": "CII", "quality": "rare", "legacyMount": false, "equipPower": "", "combatPower": "", "qualitySort": 3 },
    { "itemName": "Medium Tiger", "slots": "BBE", "quality": "rare", "legacyMount": false, "equipPower": "", "combatPower": "", "qualitySort": 3 },
    { "itemName": "Medium Waterdeep Horse", "slots": "BBI", "quality": "rare", "legacyMount": false, "equipPower": "", "combatPower": "", "qualitySort": 3 },
    { "itemName": "Medium White Horse", "slots": "BBI", "quality": "rare", "legacyMount": false, "equipPower": "", "combatPower": "", "qualitySort": 3 },
    { "itemName": "Medium Worg", "slots": "RRE", "quality": "rare", "legacyMount": false, "equipPower": "", "combatPower": "", "qualitySort": 3 },
    { "itemName": "Moonbear", "slots": "BII", "quality": "rare", "legacyMount": false, "equipPower": "", "combatPower": "", "qualitySort": 3 },
    { "itemName": "Moss-daubed Horse", "slots": "RIE", "quality": "rare", "legacyMount": false, "equipPower": "", "combatPower": "", "qualitySort": 3 },
    { "itemName": "Neverwinter Champion's Charger", "slots": "IEE", "quality": "rare", "legacyMount": false, "equipPower": "", "combatPower": "", "qualitySort": 3 },
    { "itemName": "Panther", "slots": "CCE", "quality": "rare", "legacyMount": false, "equipPower": "", "combatPower": "", "qualitySort": 3 },
    { "itemName": "Poisonous Looking Spider", "slots": "BBE", "quality": "rare", "legacyMount": false, "equipPower": "", "combatPower": "", "qualitySort": 3 },
    { "itemName": "Polar Bear", "slots": "CEE", "quality": "rare", "legacyMount": false, "equipPower": "", "combatPower": "", "qualitySort": 3 },
    { "itemName": "Reanimated Destrier", "slots": "IEE", "quality": "rare", "legacyMount": false, "equipPower": "", "combatPower": "", "qualitySort": 3 },
    { "itemName": "Sabino Destrier", "slots": "RBI", "quality": "rare", "legacyMount": false, "equipPower": "", "combatPower": "", "qualitySort": 3 },
    { "itemName": "Small Forest Stag", "slots": "RBI", "quality": "rare", "legacyMount": false, "equipPower": "", "combatPower": "", "qualitySort": 3 },
    { "itemName": "Snowclad Manticore", "slots": "CRE", "quality": "rare", "legacyMount": false, "equipPower": "", "combatPower": "", "qualitySort": 3 },
    { "itemName": "Soot Tribal Lion", "slots": "IRU", "quality": "rare", "legacyMount": false, "equipPower": "", "combatPower": "", "qualitySort": 3 },
    { "itemName": "Suratuk's Blue Strider", "slots": "BIU", "quality": "rare", "legacyMount": false, "equipPower": "", "combatPower": "", "qualitySort": 3 },
    { "itemName": "Suratuk's Giant Sunset Crab", "slots": "RBI", "quality": "rare", "legacyMount": false, "equipPower": "", "combatPower": "", "qualitySort": 3 },
    { "itemName": "Suratuk's Jungle Spider", "slots": "CRI", "quality": "rare", "legacyMount": false, "equipPower": "", "combatPower": "", "qualitySort": 3 },
    { "itemName": "Suratuk's Orange Tarantula", "slots": "BBE", "quality": "rare", "legacyMount": false, "equipPower": "", "combatPower": "", "qualitySort": 3 },
    { "itemName": "Suratuk's Red-Dusted Axebeak", "slots": "CIR", "quality": "rare", "legacyMount": false, "equipPower": "", "combatPower": "", "qualitySort": 3 },
    { "itemName": "Suratuk's Ruby Strider", "slots": "RBR", "quality": "rare", "legacyMount": false, "equipPower": "", "combatPower": "", "qualitySort": 3 },
    { "itemName": "Suratuk's Teal Spider", "slots": "CRI", "quality": "rare", "legacyMount": false, "equipPower": "", "combatPower": "", "qualitySort": 3 },
    { "itemName": "Trained Grizzly", "slots": "RRB", "quality": "rare", "legacyMount": false, "equipPower": "", "combatPower": "", "qualitySort": 3 },
    { "itemName": "Tuigan Courser", "slots": "BBI", "quality": "rare", "legacyMount": false, "equipPower": "", "combatPower": "", "qualitySort": 3 },
    { "itemName": "Water Horse", "slots": "RII", "quality": "rare", "legacyMount": false, "equipPower": "", "combatPower": "", "qualitySort": 3 },
    { "itemName": "Wolf of the Wild Hunt", "slots": "RIE", "quality": "rare", "legacyMount": false, "equipPower": "", "combatPower": "", "qualitySort": 3 },
    { "itemName": "Amnian Horse", "slots": "IU", "quality": "uncommon", "legacyMount": false, "equipPower": "", "combatPower": "", "qualitySort": 4 },
    { "itemName": "Amphail Fancy Horse", "slots": "RU", "quality": "uncommon", "legacyMount": false, "equipPower": "", "combatPower": "", "qualitySort": 4 },
    { "itemName": "Armored Boar", "slots": "BU", "quality": "uncommon", "legacyMount": false, "equipPower": "", "combatPower": "", "qualitySort": 4 },
    { "itemName": "Ashen Brindle Horse", "slots": "CU", "quality": "uncommon", "legacyMount": false, "equipPower": "", "combatPower": "", "qualitySort": 4 },
    { "itemName": "Autumn Stag", "slots": "CU", "quality": "uncommon", "legacyMount": false, "equipPower": "", "combatPower": "", "qualitySort": 4 },
    { "itemName": "Bay Zakharan Horse", "slots": "RU", "quality": "uncommon", "legacyMount": false, "equipPower": "", "combatPower": "", "qualitySort": 4 },
    { "itemName": "Black Horse", "slots": "RU", "quality": "uncommon", "legacyMount": false, "equipPower": "", "combatPower": "", "qualitySort": 4 },
    { "itemName": "Blue Ribbon Pig", "slots": "RU", "quality": "uncommon", "legacyMount": false, "equipPower": "", "combatPower": "", "qualitySort": 4 },
    { "itemName": "Calimshan Horse", "slots": "BU", "quality": "uncommon", "legacyMount": false, "equipPower": "", "combatPower": "", "qualitySort": 4 },
    { "itemName": "Crag Cat", "slots": "BU", "quality": "uncommon", "legacyMount": false, "equipPower": "", "combatPower": "", "qualitySort": 4 },
    { "itemName": "Dappled Riding Horse", "slots": "IU", "quality": "uncommon", "legacyMount": false, "equipPower": "", "combatPower": "", "qualitySort": 4 },
    { "itemName": "Deinonychus", "slots": "BU", "quality": "uncommon", "legacyMount": false, "equipPower": "", "combatPower": "", "qualitySort": 4 },
    { "itemName": "Demon Sled", "slots": "CU", "quality": "uncommon", "legacyMount": false, "equipPower": "", "combatPower": "", "qualitySort": 4 },
    { "itemName": "Electric Tiger", "slots": "RI", "quality": "uncommon", "legacyMount": true, "equipPower": null, "combatPower": null, "qualitySort": 4 },
    { "itemName": "Fey Wolf", "slots": "CU", "quality": "uncommon", "legacyMount": false, "equipPower": "", "combatPower": "", "qualitySort": 4 },
    { "itemName": "Frozen Polar Bear", "slots": "RU", "quality": "uncommon", "legacyMount": false, "equipPower": "", "combatPower": "", "qualitySort": 4 },
    { "itemName": "Gilded White Steed", "slots": "RU", "quality": "uncommon", "legacyMount": false, "equipPower": "", "combatPower": "", "qualitySort": 4 },
    { "itemName": "Grey Horse", "slots": "", "quality": "uncommon", "legacyMount": false, "equipPower": "", "combatPower": "", "qualitySort": 4 },
    { "itemName": "Grullo Zakharan Horse", "slots": "", "quality": "uncommon", "legacyMount": false, "equipPower": "", "combatPower": "", "qualitySort": 4 },
    { "itemName": "Ice Panther", "slots": "BU", "quality": "uncommon", "legacyMount": false, "equipPower": "", "combatPower": "", "qualitySort": 4 },
    { "itemName": "Inferno Nightmare", "slots": "IU", "quality": "uncommon", "legacyMount": false, "equipPower": "", "combatPower": "", "qualitySort": 4 },
    { "itemName": "Jubilee Parade Horse", "slots": "RU", "quality": "uncommon", "legacyMount": false, "equipPower": "", "combatPower": "", "qualitySort": 4 },
    { "itemName": "Jubilee Unicorn", "slots": "RU", "quality": "uncommon", "legacyMount": false, "equipPower": "", "combatPower": "", "qualitySort": 4 },
    { "itemName": "Onyx Horse", "slots": "IU", "quality": "uncommon", "legacyMount": true, "equipPower": null, "combatPower": null, "qualitySort": 4 },
    { "itemName": "Pale Horse", "slots": "EU", "quality": "uncommon", "legacyMount": false, "equipPower": "", "combatPower": "", "qualitySort": 4 },
    { "itemName": "Pharaoh Steed", "slots": "BU", "quality": "uncommon", "legacyMount": false, "equipPower": "", "combatPower": "", "qualitySort": 4 },
    { "itemName": "Rainbow Starry Panther", "slots": "IU", "quality": "uncommon", "legacyMount": true, "equipPower": null, "combatPower": null, "qualitySort": 4 },
    { "itemName": "Shadow Wolf", "slots": "CU", "quality": "uncommon", "legacyMount": false, "equipPower": "", "combatPower": "", "qualitySort": 4 },
    { "itemName": "Starry Panther", "slots": "CU", "quality": "uncommon", "legacyMount": false, "equipPower": "", "combatPower": "", "qualitySort": 4 },
    { "itemName": "Stormraider Horse", "slots": "IU", "quality": "uncommon", "legacyMount": false, "equipPower": "", "combatPower": "", "qualitySort": 4 },
    { "itemName": "Sunite Steed", "slots": "EU", "quality": "uncommon", "legacyMount": false, "equipPower": "", "combatPower": "", "qualitySort": 4 },
    { "itemName": "Tethyr Horse", "slots": "EU", "quality": "uncommon", "legacyMount": false, "equipPower": "", "combatPower": "", "qualitySort": 4 },
    { "itemName": "Tribal Polar Bear", "slots": "BI", "quality": "uncommon", "legacyMount": false, "equipPower": "", "combatPower": "", "qualitySort": 4 },
    { "itemName": "White Horse", "slots": "IU", "quality": "uncommon", "legacyMount": false, "equipPower": "", "combatPower": "", "qualitySort": 4 },
    { "itemName": "Winter Sled", "slots": "EU", "quality": "uncommon", "legacyMount": false, "equipPower": "", "combatPower": "", "qualitySort": 4 },
    { "itemName": "Winter Stag", "slots": "CU", "quality": "uncommon", "legacyMount": true, "equipPower": null, "combatPower": null, "qualitySort": 4 },
    { "itemName": "Winter Wolf", "slots": "BU", "quality": "uncommon", "legacyMount": false, "equipPower": "", "combatPower": "", "qualitySort": 4 },
    { "itemName": "Appaloosa Horse", "slots": "CI", "quality": "common", "legacyMount": false, "equipPower": "", "combatPower": "", "qualitySort": 5 },
    { "itemName": "Boar", "slots": "RI", "quality": "common", "legacyMount": true, "equipPower": null, "combatPower": null, "qualitySort": 5 },
    { "itemName": "Brindle Horse", "slots": "CB", "quality": "common", "legacyMount": false, "equipPower": "", "combatPower": "", "qualitySort": 5 },
    { "itemName": "Palomino Horse", "slots": "RB", "quality": "common", "legacyMount": false, "equipPower": "", "combatPower": "", "qualitySort": 5 },
    { "itemName": "Sabino Horse", "slots": "RE", "quality": "common", "legacyMount": false, "equipPower": "", "combatPower": "", "qualitySort": 5 },
    { "itemName": "Waterdeep Horse", "slots": "IE", "quality": "common", "legacyMount": false, "equipPower": "", "combatPower": "", "qualitySort": 5 }];
